// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI still generates SQLite migrations against a local file.
    // Runtime access to Turso is configured separately in src/lib/db.ts.
    url: process.env["LOCAL_DATABASE_URL"] || "file:./prisma/dev.db",
  },
});
